# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sandbox.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/sandbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/sandbox.proto\x12\x06\x64\x63odex\"-\n\x0b\x43odeRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\":\n\x0c\x45xecutionLog\x12\x14\n\x0cstdout_chunk\x18\x01 \x01(\t\x12\x14\n\x0cstderr_chunk\x18\x02 \x01(\t2F\n\x0c\x43odeExecutor\x12\x36\n\x07\x45xecute\x12\x13.dcodex.CodeRequest\x1a\x14.dcodex.ExecutionLog0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sandbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODEREQUEST']._serialized_start=31
  _globals['_CODEREQUEST']._serialized_end=76
  _globals['_EXECUTIONLOG']._serialized_start=78
  _globals['_EXECUTIONLOG']._serialized_end=136
  _globals['_CODEEXECUTOR']._serialized_start=138
  _globals['_CODEEXECUTOR']._serialized_end=208
# @@protoc_insertion_point(module_scope)
